### ISSUE TITLE
Release Management review

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/SimpleEdgeDiscovery#32]
**Problem description**

Issue to request Release Management review of SimpleEdgeDiscovery 0.11.0-rc.1

**Expected action**

Release Management to kindly review PR #31 , to allow merge to main / release with tag r1.1

**Additional context**

**Comment by hdamker** [comment]
In addition to #31 it is also necessary to rework the CHANGELOG.md, e.g.
* change title of release towards r1.1
* correct links accordingly so that they work with tag r1.1
* change https://github.com/camaraproject/SimpleEdgeDiscovery/compare/r1.4...r1.5 to something which works
* if possible align the format more with the example within ReleaseManagement. The list of addressed issues might of less help
* add some words about the history of the API and where the previous releases v0.8.1 and v0.9.3-rc can be found

**Comment by tanjadegroot** [comment]
CHANGELOG.md review - additional comments:

The API definition(s) are based on
* Commonalities v0.4-rc.1  --> r0.4.0-rc.1  // missing the patch nr 0)
* Identity and Consent Management v0.2.0-rc.1 

NOTE: the ICM reference is OK (they will change to the correct release tag (r0.2.0-xx in the next (pre-)release)

**Comment by tanjadegroot** [comment]
README.md: needs to be updated:

- include the link to the pre-release tag
- include the link to the wiki

**Comment by tanjadegroot** [comment]
Need to do a last cross check with @hdamker on some commonalities and ICM checks needed, but it seem this is in great shape for M3.

**Comment by Kevsy** [comment]
Thanks for the review Tanja - additional comments above for CHANGELOG and README now committed.

**Comment by tanjadegroot** [comment]
Please add @release-management_maintainers to this PR once the team considers the PR is ready.

**Comment by Kevsy** [comment]
Release Management review completion confirmed: https://github.com/camaraproject/SimpleEdgeDiscovery/pull/31#issuecomment-2253158113
